name: Run AI Content Generation 3 Times Sequentially

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      max-parallel: 1
      matrix:
        run_count: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run content generation script (Run ${{ matrix.run_count }} of 3)
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Commit and push if files changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: AI-generated content (run ${{ matrix.run_count }}/3)"
          file_pattern: index.html post_history.json
